export const messageDropDownNav = [
  {
    id: 1,
    name: "Wade Warren",
    message: "Congrats on your work anniversary!",
    createdDate: "20 minutes ago",
    numberOfMessages: 2,
    avatar: "/assets/navigation/profile-image.png",
  },
  {
    id: 2,
    name: "John Doe",
    message: "Happy Birthday!",
    createdDate: "1 hour ago",
    numberOfMessages: 0,
    avatar: "/assets/navigation/profile-image.png",
  },
  {
    id: 3,
    name: "Jane Smith",
    message: "Just got a new job!",
    createdDate: "2 hours ago",
    numberOfMessages: 0,
    avatar: "/assets/navigation/profile-image.png",
  },
  {
    id: 4,
    name: "Alice Johnson",
    message: "Starting a new project.",
    createdDate: "3 hours ago",
    numberOfMessages: 3,
    avatar: "/assets/navigation/profile-image.png",
  },
  {
    id: 5,
    name: "Bob Brown",
    message: "Going on vacation next week.",
    createdDate: "4 hours ago",
    numberOfMessages: 0,
    avatar: "/assets/navigation/profile-image.png",
  },
];
