export const notifications = [
  {
    id: 1,
    name: "Catalin Pit",
    avatar: "/assets/navigation/avatar-2.png",
    type: "comment",
    typeIcon: "/assets/navigation/comment.png",
    typeText: "commented on your post",
    text: "Great ebook and giveaway!",
    title: "Hipnode Book Giveaway: The standout Developer by Randall Kanna",
    date: "22 Feb",
    time: "3:26pm",
  },
  {
    id: 2,
    name: "Jubed Ahmed",
    avatar: "/assets/navigation/avatar-3.png",
    type: "meetup",
    typeIcon: "/assets/navigation/post.png",
    typeText: "published a meetup",
    text: "",
    title: "Best Color Palette Generators for UI Designers and Developers",
    date: "17 Feb",
    time: "10:48pm",
  },
  {
    id: 3,
    name: "Tushar Srivastava",
    avatar: "/assets/navigation/avatar-4.png",
    type: "reaction",
    typeIcon: "/assets/navigation/heart.png",
    typeText: "liked your post",
    text: "",
    title:
      "Best Color Palette Generators for UI Designers and Developers5 Key UI Design Principles for Beginners",
    date: "13 Feb",
    time: "1:54am",
  },
  {
    id: 4,
    name: "Catalin Pit",
    avatar: "/assets/navigation/avatar-2.png",
    type: "comment",
    typeIcon: "/assets/navigation/comment.png",
    typeText: "commented on your post",
    text: "Great ebook and giveaway!",
    title: "Hipnode Book Giveaway: The standout Developer by Randall Kanna",
    date: "22 Feb",
    time: "3:26pm",
  },
  {
    id: 5,
    name: "Jubed Ahmed",
    avatar: "/assets/navigation/avatar-3.png",
    type: "meetup",
    typeIcon: "/assets/navigation/post.png",
    typeText: "published a meetup",
    text: "",
    title: "Best Color Palette Generators for UI Designers and Developers",
    date: "17 Feb",
    time: "10:48pm",
  },
  {
    id: 6,
    name: "Tushar Srivastava",
    avatar: "/assets/navigation/avatar-4.png",
    type: "reaction",
    typeIcon: "/assets/navigation/heart.png",
    typeText: "liked your post",
    text: "",
    title:
      "Best Color Palette Generators for UI Designers and Developers5 Key UI Design Principles for Beginners",
    date: "13 Feb",
    time: "1:54am",
  },
];
