export const newAndPopularMobile = [
  {
    id: 1,
    icon: '/assets/leftSideBarHome/new.svg',
    title: 'Newest',

    isFollowingNumberHidden: true,
  },
  {
    id: 2,
    icon: '/assets/leftSideBarHome/popular.svg',
    title: 'Popular',

    isFollowingNumberHidden: true,
  },
  {
    id: 3,
    title: 'Following',
    icon: '/assets/leftSideBarHome/follow.svg',
    isFollowingNumberHidden: false,
  },
];

export const newAndPopular = [
  {
    id: 1,
    icon: '/assets/leftSideBarHome/new.svg',
    title: 'Newest and Recent',
    text: 'Find the latest update',
    isFollowingNumberHidden: true,
  },
  {
    id: 2,
    icon: '/assets/leftSideBarHome/popular.svg',
    title: 'Popular of the day',
    text: 'Shots Featured Today by Creators',
    isFollowingNumberHidden: true,
  },
  {
    id: 3,
    title: 'Following',
    icon: '/assets/leftSideBarHome/follow.svg',
    text: 'Explore from your favorite person',
    isFollowingNumberHidden: false,
  },
];

export const popularTags = [
  {
    id: 1,
    title: 'javascript',
    icon: '/assets/leftSideBarHome/javascript.svg',
    noOfPosts: 82645,
    text: 'Posted by this tag',
    isFollowingNumberHidden: true,
    bgColor: 'yellow',
    hashtag: true,
  },
  {
    id: 2,
    title: 'bitcoin',
    icon: '/assets/leftSideBarHome/bitcoin.svg',
    noOfPosts: 65523,
    text: 'Posted | Trending',
    isFollowingNumberHidden: true,
    bgColor: 'red',
    hashtag: true,
  },
  {
    id: 3,
    title: 'design',
    icon: '/assets/leftSideBarHome/design.svg',
    noOfPosts: 45637,
    text: 'Trending in Bangladesh',
    isFollowingNumberHidden: true,
    bgColor: 'blue',
    hashtag: true,
  },
  {
    id: 4,
    title: 'blogging',
    icon: '/assets/leftSideBarHome/blogging.svg',
    noOfPosts: 67645,
    text: 'Posted by this tag',
    isFollowingNumberHidden: true,
    bgColor: 'yellow',
    hashtag: true,
  },
  {
    id: 5,
    title: 'tutorial',
    icon: '/assets/leftSideBarHome/tutorial.svg',
    noOfPosts: 42625,
    text: 'Trending in Bangladesh',
    isFollowingNumberHidden: true,
    bgColor: 'green',
    hashtag: true,
  },
  {
    id: 6,
    title: 'seo',
    icon: '/assets/leftSideBarHome/seo.svg',
    noOfPosts: 55645,
    text: 'Posted by this tag',
    isFollowingNumberHidden: true,
    bgColor: 'purple',
    hashtag: true,
  },
];

export const pinnedGroups = [
  {
    id: 1,
    title: 'javascript',
    icon: '/assets/leftSideBarHome/javascript2.svg',
    noOfPosts: 82645,
    text: 'Posted by this tag',
    hashtag: true,
    isFollowingNumberHidden: true,
    bgColor: 'transparent',
  },
  {
    id: 2,
    title: 'bitcoin',
    icon: '/assets/leftSideBarHome/bitcoin2.svg',
    noOfPosts: 65523,
    text: 'Posted Trending',
    hashtag: true,
    isFollowingNumberHidden: true,
    bgColor: 'transparent',
  },
  {
    id: 3,
    title: 'design',
    icon: '/assets/leftSideBarHome/design2.svg',
    noOfPosts: 45637,
    text: 'Trending in Bangladesh',
    hashtag: true,
    isFollowingNumberHidden: true,
    bgColor: 'transparent',
  },
  {
    id: 4,
    title: 'blogging',
    icon: '/assets/leftSideBarHome/blogging2.svg',
    noOfPosts: 67645,
    text: 'Posted by this tag',
    hashtag: true,
    isFollowingNumberHidden: true,
    bgColor: 'transparent',
  },
];
