export const postDummyData = [
  {
    id: 1,
    title:
      'The 4-step SEO framework that led to a 1000% increase in traffic. Let’s talk about blogging and SEO...',
    views: 244564,
    likes: 10290,
    comments: 184,
    name: 'AR Jakir',
    createdDate: '3 days ago',
    avatar: '/user-avatar.svg',
    tags: ['finance', 'bitcoin', 'crypto'],
    online: true,
    isLiked: true,
    mainImage: '/bitcoin.png',
  },
  {
    id: 2,
    title: 'How to Master Social Media Marketing in 2023',
    views: 89045,
    likes: 7800,
    comments: 112,
    name: 'Emily Smith',
    createdDate: '5 days ago',
    avatar: '/user-avatar.svg',
    tags: ['social media', 'marketing', 'digital'],
    online: false,
    isLiked: false,
    mainImage: '/bitcoin.png',
  },
  {
    id: 3,
    title: 'The Ultimate Guide to Cooking Delicious Vegan Dishes',
    views: 54213,
    likes: 9200,
    comments: 167,
    name: 'Alicia Brown',
    createdDate: '1 week ago',
    avatar: '/user-avatar.svg',
    tags: ['vegan', 'cooking', 'recipes'],
    online: true,
    isLiked: false,
    mainImage: '/bitcoin.png',
  },
  {
    id: 4,
    title: 'A Deep Dive into Machine Learning Algorithms',
    views: 123789,
    likes: 15000,
    comments: 348,
    name: 'John Miller',
    createdDate: '2 weeks ago',
    avatar: '/user-avatar.svg',
    tags: ['machine learning', 'AI', 'algorithms'],
    online: true,
    isLiked: true,
    mainImage: '/bitcoin.png',
  },
  {
    id: 5,
    title: 'Exploring the Wonders of Astrophysics',
    views: 67589,
    likes: 9800,
    comments: 225,
    name: 'Luna Martinez',
    createdDate: '2 weeks ago',
    avatar: '/user-avatar.svg',
    tags: ['astrophysics', 'space', 'science'],
    online: true,
    isLiked: false,
    mainImage: '/bitcoin.png',
  },
  {
    id: 6,
    title: 'Traveling the World: Unforgettable Adventures in 2023',
    views: 98765,
    likes: 12500,
    comments: 297,
    name: 'David Johnson',
    createdDate: '3 weeks ago',
    avatar: '/user-avatar.svg',
    tags: ['travel', 'adventure', 'explore'],
    online: true,
    isLiked: true,
    mainImage: '/bitcoin.png',
  },
  {
    id: 7,
    title: 'Healthy Lifestyle: Tips for a Balanced Life',
    views: 45678,
    likes: 8300,
    comments: 138,
    name: 'Olivia Davis',
    createdDate: '4 weeks ago',
    avatar: '/user-avatar.svg',
    tags: ['health', 'wellness', 'lifestyle'],
    online: false,
    isLiked: false,
    mainImage: '/bitcoin.png',
  },
  {
    id: 8,
    title: 'The Art of Photography: Capturing the Beauty of Nature',
    views: 34567,
    likes: 7500,
    comments: 176,
    name: 'Daniel Lee',
    createdDate: '1 month ago',
    avatar: '/user-avatar.svg',
    tags: ['photography', 'nature', 'art'],
    online: true,
    isLiked: true,
    mainImage: '/bitcoin.png',
  },
];
