export const postDummyData = [
  {
    id: 1,
    title:
      'The 4-step SEO framework that led to a 1000% increase in traffic. Let’s talk about blogging and SEO...',
    views: 244564,
    likes: 10290,
    comments: 184,
    name: 'AR Jakir',
    createdDate: '3 days ago',
    avatar: '/user-avatar.svg',
    tags: ['finance', 'bitcoin', 'crypto'],
    online: true,
    isLiked: true,
    mainImage: '/bitcoin.png',
  },
  {
    id: 2,
    title:
      'The 4-step SEO framework that led to a 1000% increase in traffic. Let’s talk about blogging and SEO...',
    views: 244564,
    likes: 10290,
    comments: 184,
    name: 'AR Jakir',
    createdDate: '3 days ago',
    avatar: 'https://github.com/shadcn.png',
    tags: ['finance', 'bitcoin', 'seo'],
    online: true,
    isLiked: true,
    mainImage: '/bitcoin.png',
  },
  {
    id: 3,
    title: 'The importance of diversifying your investment portfolio',
    views: 12345,
    likes: 678,
    comments: 90,
    name: 'John Doe',
    createdDate: '1 week ago',
    avatar: '/user-avatar2.svg',
    tags: ['finance', 'investing', 'portfolio'],
    online: false,
    isLiked: false,
    mainImage: '/bitcoin.png',
  },
  {
    id: 4,
    title:
      'The future of cryptocurrency: Exploring the potential of blockchain technology',
    views: 9876,
    likes: 543,
    comments: 76,
    name: 'Jane Smith',
    createdDate: '2 days ago',
    avatar: 'https://github.com/shadcn.png',
    tags: ['crypto', 'blockchain', 'technology'],
    online: true,
    isLiked: true,
    mainImage: '/bitcoin.png',
  },
  {
    id: 5,
    title: 'The impact of social media on financial markets',
    views: 5678,
    likes: 321,
    comments: 54,
    name: 'Alex Johnson',
    createdDate: '4 hours ago',
    avatar: '/user-avatar4.svg',
    tags: ['finance', 'social media', 'markets'],
    online: true,
    isLiked: false,
    mainImage: '/bitcoin.png',
  },
  {
    id: 6,
    title: 'The rise of decentralized finance (DeFi) and its implications',
    views: 8765,
    likes: 432,
    comments: 65,
    name: 'Emily Wilson',
    createdDate: '1 day ago',
    avatar: '/user-avatar5.svg',
    tags: ['finance', 'DeFi', 'cryptocurrency'],
    online: false,
    isLiked: true,
    mainImage: '/bitcoin.png',
  },
  {
    id: 7,
    title: 'The role of artificial intelligence in financial forecasting',
    views: 3456,
    likes: 210,
    comments: 32,
    name: 'Michael Brown',
    createdDate: '5 days ago',
    avatar: '/user-avatar6.svg',
    tags: ['finance', 'AI', 'forecasting'],
    online: true,
    isLiked: false,
    mainImage: '/bitcoin.png',
  },
  {
    id: 8,
    title:
      'The power of compound interest: How it can help you grow your wealth',
    views: 6543,
    likes: 109,
    comments: 21,
    name: 'Sarah Thompson',
    createdDate: '2 weeks ago',
    avatar: 'https://github.com/shadcn.png',
    tags: ['finance', 'investing', 'wealth'],
    online: true,
    isLiked: true,
    mainImage: '/bitcoin.png',
  },
  {
    id: 9,
    title: 'The future of work: Exploring the rise of remote jobs',
    views: 4321,
    likes: 98,
    comments: 18,
    name: 'David Wilson',
    createdDate: '6 days ago',
    avatar: '/user-avatar8.svg',
    tags: ['work', 'remote', 'jobs'],
    online: false,
    isLiked: false,
    mainImage: '/bitcoin.png',
  },
  {
    id: 10,
    title: 'The impact of inflation on the economy and personal finances',
    views: 3210,
    likes: 87,
    comments: 15,
    name: 'Sophia Davis',
    createdDate: '3 weeks ago',
    avatar: 'https://github.com/shadcn.png',
    tags: ['finance', 'inflation', 'economy'],
    online: true,
    isLiked: true,
    mainImage: '/bitcoin.png',
  },
];
